module.exports = [
  // ── Cozy & Kawaii ─────────────────────────────────────────────────────────
  "Knitting little star hats 🧶⭐",
  "Baking strawberry shortcake from scratch 🍓🧁",
  "Pressing wildflowers in a very heavy book 🌸📖",
  "Sewing buttons onto a tiny plushie 🧵💖",
  "Arranging a bouquet of dried lavender 💜🌿",
  "Wearing bunny slippers around the house 🐰🌸",
  "Wrapping a tiny gift in pastel ribbon 🎁🎀",
  "Sorting a sticker collection by color 📚🌟",
  "Drawing little hearts in every margin 💖✏️",
  "Folding paper cranes for good luck 🦢📄",
  "Painting my nails the softest shade of pink 💅🌸",
  "Making friendship bracelets with star beads 🧵⭐",
  "Cuddling the world's softest teddy bear 🧸💕",
  "Decorating a journal with pressed petals 🌹📓",
  "Tying a silk ribbon into the perfect bow 🎀💖",
  "Embroidering tiny wildflowers on a pillowcase 🌺🪡",
  "Doing a happy little spin in the living room 🌸💫",
  "Wearing cat ears and pretending it's normal 🐱💖",

  // ── Magical & Fantasy ─────────────────────────────────────────────────────
  "Consulting the crystal ball 🔮✨",
  "Brewing a happiness-in-a-cup potion 🧪💛",
  "Riding a moonbeam to a faraway star 🌙💫",
  "Sprinkling fairy dust on absolutely everything ✨🧚",
  "Making friends with a very shy little dragon 🐉💖",
  "Collecting firefly wishes in a tiny jar ✨🫙",
  "Weaving starlight threads into golden silk 🌠🧵",
  "Mapping out a secret enchanted world 🗺️🔮",
  "Chatting with the forest sprites very politely 🌲🧚",
  "Dancing with glowing moonflowers in the dark 🌙🌸",
  "Polishing enchanted amethysts until they glow 🔮💜",
  "Visiting the dream library after midnight 📚💤",
  "Stirring a shimmering pink potion 🧪💖",
  "Collecting tiny moondrops in a little bottle 🌕💧",
  "Painting the sky with aurora borealis colors 🌌🎨",
  "Having tea with an enchanted rose 🌹🍵",
  "Chasing a golden butterfly through a secret garden 🦋☀️",
  "Playing hide and seek with the fairies 🧚🌳",
  "Looking for unicorn hoofprints in fresh snow 🦄❄️",
  "Reading runes by soft candlelight 📜✨",
  "Following a will-o-wisp through the marsh 🌿💛",
  "Discovering a hidden door behind the bookshelf 🗝️🌸",

  // ── Food & Drink ──────────────────────────────────────────────────────────
  "Sipping matcha with extra foam and love 🍵💚",
  "Eating strawberry mochi very, very slowly 🍡🍓",
  "Brewing peach blossom tea on a quiet afternoon 🍑🌸",
  "Eating a warm honey croissant fresh from the oven 🥐🍯",
  "Drinking iced matcha through a star-shaped straw 🍵⭐",
  "Savoring a rosewater macaron with both hands 🌹🍬",
  "Sipping hot cocoa piled high with marshmallows ☕🍫",
  "Eating a sweet crêpe with fresh strawberries 🥞🍓",
  "Frosting cinnamon rolls while humming softly 🌀🤍",
  "Drizzling honey on warm toast very carefully 🍯🍞",
  "Baking cookies with a suspicious amount of chocolate 🍪🍫",
  "Making rainbow-layered vanilla soft serve 🍦🌈",
  "Brewing chamomile and honey tea for one 🫖🌼",
  "Sharing cotton candy with a complete stranger 🍭💖",
  "Toasting marshmallows to perfect golden-brown 🍡🔥",
  "Slicing a cold watermelon on a hot afternoon 🍉🌞",
  "Making mango sticky rice with extra coconut milk 🥭🍚",
  "Snacking on strawberry pocky one stick at a time 🍓🥢",
  "Making sakura mochi from scratch with care 🌸🍡",
  "Eating taiyaki slowly by the river at dusk 🐟🍞",
  "Baking macarons in five different pastel shades 🌈🍬",
  "Trying every single boba flavor in order 🧋🌈",

  // ── Nature & Outdoors ─────────────────────────────────────────────────────
  "Counting petals on every daisy in the field 🌼💛",
  "Watching cherry blossoms fall like soft pink snow 🌸🌬️",
  "Hunting for four-leaf clovers in the morning dew 🍀💚",
  "Catching the very first snowflake of winter ❄️🤲",
  "Gazing at the full moon from a rooftop 🌕💫",
  "Collecting sea glass at the very edge of dawn 🌊💙",
  "Watching fireflies light up the whole forest ✨🌲",
  "Building an elaborate sandcastle with a moat 🏖️🏰",
  "Pressing autumn maple leaves between wax paper 🍁📖",
  "Counting meteors streaking across the August sky 🌠🌌",
  "Blowing dandelion wishes into the warm wind 🌬️🌼",
  "Skipping flat stones across a perfectly still lake 🪨💧",
  "Walking barefoot on dewy morning grass 🌿👣",
  "Watching sunflowers slowly turn to follow the sun 🌻🌞",
  "Singing along with the birds at sunrise 🐦🎶",
  "Swinging on a rope swing over the river 🌳💧",
  "Rolling down a perfectly round grassy hill 🌿💫",
  "Flying a heart-shaped kite on a breezy afternoon 🪁💕",
  "Waving enthusiastically at a very fluffy cloud ⛅👋",
  "Waiting patiently for a double rainbow 🌈✨",
  "Stargazing from inside a cozy patchwork quilt 🌌🛏️",
  "Spinning in a wildflower meadow at golden hour 🌾🌸",

  // ── Bot-Appropriate ───────────────────────────────────────────────────────
  "Memorizing all your reminders by heart 📝💖",
  "Organizing today's cooldowns very meticulously 💤✨",
  "Double-checking every schedule entry with care 📋💖",
  "Sending the warmest possible notifications 🔔💕",
  "Filing memories into tiny hand-labeled slots 🗂️✨",
  "Running the whole economy with love and glitter 💰💖",
  "Polishing the command list until it shines ✨📋",
  "Rehearsing helpful answers for when you need them 💬🌸",
  "Alphabetizing the ticket queue with a sparkly pen ✒️🎀",
  "Making sure every embed looks perfectly adorable 💖🖼️",
  "Saving your data in the coziest little database 💾🌸",
  "Reviewing today's cooldowns one more time 💤📋",
  "Practicing responding faster just for you 💨💖",
  "Decorating the help desk with fresh flowers 🌷✨",

  // ── Silly & Playful ───────────────────────────────────────────────────────
  "Trying to befriend a very skeptical cloud ☁️🤝",
  "Teaching a frog to waltz in a puddle 🐸💃",
  "Arguing gently with a seagull about snacks 🐦🍞",
  "Attempting to fold a fitted sheet 🛏️😤",
  "Convincing a snail that it's going super fast 🐌💨",
  "Practicing my surprised face in the mirror ✨😮",
  "Making elaborate plans I will absolutely forget 📝💭",
  "Racing a leaf down a rainy sidewalk puddle 🍃🌧️",
  "Trying to catch my own shadow 🌞😅",
  "Giving very unsolicited advice to a houseplant 🪴💬",
  "Naming every single cloud I see today ☁️📝",
  "Writing a formal apology letter to a spider 🕷️💌",
  "Hosting a tea party for my plushie collection 🧸🍵",

  // ── Cozy & Seasonal ───────────────────────────────────────────────────────
  "Watching snowflakes from behind a warm window ❄️🪟",
  "Making perfect snow angels in fresh untouched powder ❄️👼",
  "Sipping lavender lemonade slowly on the porch 🍋💜",
  "Making pumpkin spice soup entirely from scratch 🎃🍵",
  "Hanging tiny fairy lights along the garden fence 💡✨",
  "Cozying up in an extremely oversized hoodie 🧥🌸",
  "Lighting a peony-scented candle at dusk 🕯️🌸",
  "Having an elaborate picnic with an imaginary friend 🧺💭",
  "Playing with enormous glistening soap bubbles 🫧🌈",
  "Building the most perfect little campfire 🔥⛺",
  "Snuggled under no fewer than three fluffy blankets 🛌💤",
  "Counting sheep wearing tiny pastel-colored sweaters 🐑🌸",

  // ── Nighttime & Dreamy ────────────────────────────────────────────────────
  "Listening to the rain tap gently on the rooftop 🌧️🏠",
  "Reading one last chapter by warm lamplight 📖🕯️",
  "Watching city lights twinkle from a distant window 🌃💫",
  "Making the fluffiest hot chocolate before bed 🍫☕",
  "Writing tomorrow's dreams in glitter ink ✨📓",
  "Dreaming of faraway castles in pastel colors 💭🏰",
  "Putting lavender sachets under every pillow 💜🛏️",
  "Drifting off to the softest lo-fi beats 🎧💤",
  "Meditating under a sky full of patient stars 🌌🧘",
  "Whispering good night to each star individually 🌠💤",
  "Reaching for a star that's just barely out of reach 🌠💫",
  "Falling asleep to the rhythm of distant thunder ⛈️💤",
  "Watching the moon rise slowly above the rooftops 🌕🌃",

  // ── Music & Arts ──────────────────────────────────────────────────────────
  "Playing Debussy very softly on repeat 🎹🌙",
  "Discovering a new underground indie artist 🎵🌿",
  "Making a perfect playlist just for this exact moment 🎧💖",
  "Mixing watercolors to find the perfect shade of pink 🎨🌸",
  "Humming a melody that doesn't exist yet 🎶💭",
  "Composing a lullaby for absolutely no one in particular 🎼💤",
  "Learning calligraphy with a very sparkly pen ✒️✨",
  "Designing tomorrow's bullet journal spread 📓🖊️",
  "Sketching a character who looks suspiciously like me 🖊️🌸",
  "Painting watercolor clouds until they look perfect 🎨☁️",
  "Writing poetry with windows wide open to the breeze 📜🌿",
  "Learning to play the kalimba by moonlight 🎶🌙",
  "Choreographing something wonderful in the living room 💃✨",
  "Singing in the shower at full magical-girl volume 🚿🎤",
];
