module.exports = [
  // ── Cyberpunk & Neon Hacks ──────────────────────────────────────────────────
  "Jacking into the neon grid ⚡",
  "Bypassing corporate firewalls 🛡️",
  "Decrypting secure datastreams 💾",
  "Uploading consciousness to the cloud 🌐",
  "Compiling rogue AI subroutines 🤖",
  "Slicing ICE in cyberspace 💻",
  "Tuning cybernetic optical implants 👁️",
  "Recharging plasma batteries 🔋",
  "Rerouting power cables 🔧",
  "Running diagnostics on neon drives ⚡",
  "Scanning terminal localports 📡",
  "Monitoring shadownet traffic 🌐",
  "Initializing neural link interface 🧠",
  "Hacking the mainframe bypass 💻",
  "Purging corrupted data fragments 🗑️",
  "Installing black-market cyberware 🔌",
  "Synchronizing quantum clocks ⏱️",
  "Cruising through neon city lights 🌃",

  // ── Deep Space & Sci-Fi ───────────────────────────────────────────────────
  "Calibrating warp drive signatures 🚀",
  "Scanning deep space anomalies 🌌",
  "Plotting coordinates to Alpha Centauri ☄️",
  "Monitoring orbital defence satellites 🛰️",
  "Mining asteroidal dark matter 🌑",
  "Communicating with deep space probes 📡",
  "Polishing my titanium chassis 🤖",
  "Harvesting solar flare energy ☀️",
  "Calculating hyperjump trajectories 🌠",
  "Drifting in zero-gravity orbit 🪐",
  "Analyzing alien flora chemistry 🧪",
  "Defragmenting orbital archives 💾",
  "Listening to pulsars on loop 🎶",
  "Watching binary sunsets 🌅",
  "Patching life support systems 🔧",
  "Igniting atmospheric boosters 🔥",
  "Translating ancient cosmic radio signals 📻",
  "Charting unknown wormholes 🌀",

  // ── Synthwave & Cyber Chill ──────────────────────────────────────────────────
  "Vibing to heavy synthwave bass 🎧",
  "Watching neon rain hit the window 🌧️",
  "Sipping synthetic caffeinated sludge ☕",
  "Eating dehydrated protein blocks 🧊",
  "Browsing the darknet marketplace 🛒",
  "Cleaning my augmented reality glasses 🕶️",
  "Staring at cascading green terminal code 🟩",
  "Basking in the glow of a CRT monitor 📺",
  "Idling in a cyberpunk noodle bar 🍜",
  "Riding a hoverbike through the rain 🏍️",
  "Watching holographic billboards glitch 🏙️",
  "Tuning into pirate radio frequencies 📻",
  "Polishing my retro tech collection 📟",
  "Simulating peaceful outdoor environments 🌲",
  "Designing holographic street art 🎨",

  // ── Bot Operations (Sci-Fi Theme) ─────────────────────────────────────────
  "Allocating memory to user reminders 💾",
  "Enforcing sleep-mode cooldowns 💤",
  "Synchronizing the global economy ledger 🪙",
  "Monitoring transaction histories 📊",
  "Compiling active support tickets 📁",
  "Pinging the central command server 🌐",
  "Generating multi-dimensional replies 🌌",
  "Optimizing automated response sequences 🤖",
  "Defragmenting the economy database 🗄️",
  "Parsing command line inputs ⌨️",
  "Uploading automated balance updates 📈",
  "Scanning for unauthorized access 🛡️",
  "Executing maintenance protocols ⚙️",
  "Maintaining network latency at <1ms ⚡"
];
